language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palettes_test;' -U postgres
- knex migrate:latest --env=test
- knex seed:run --env=test
notification:
- email: false
deploy:
  provider: heroku
  api_key:
    secure: LzVkNQhOz0vyNhDGzA0+nro+ygD9VIwEYKYVoPTCoCIAXAUsoH1hsX3Zd8VAw4SSAM/4T1aJfsrCp1VjZjNjq7jbq/50Kgn4VlPKsexmE7Bv0YMSs6tUoTN1FBFMmObfRIL6IbIgzyGqlVpCaYUk9SfgyMk0wOz5DL9n4VLELgyY04q37ZzGlHFWHFM2OAWumnUqJpD6SUZhoXgiiFIX5GL4pV9CqUhq8rYmvtnwD7dMUPISMGIveSAz/7W+ZpJlQlqNLhyScVgnlDrkMmu/lwbvQVmPjIRhzht2ZRQtcv+4C9ThwpLq8PcWJsXyHxFt9hqO307UBQ9KUjY+j8X/tegjFseT9gFNwngCb6M2gMrmaSMMDwzPE8JBy50qHBT9zwdX05mZkivl/n0bKLoQTVR0IHe+IcXg+m2NYTRIWUZ0YOGiet+dMwaxRVHQjyi27RQBCmy7zd0/8F5fjNIPYQLXOAxJO2ZBDDCPgV7dA85mTLKY0efkWccYZMSVADAy67f7X//L/blTry5YFbukUY0/8R9XxUEY2gbPdP+koqLidT1Dn5mt/t3AkidCrqWZB2+OXUR+9AEGy46KY/n8VeJJS9obHQdv2nO2vhoCTt9KvPFSH/la6d0Z0zODfQdRrQ9IqYFfkpljCiQNi5IptvEWsEiEL3g0ckulJHz//JY=
app: palette-picker-backend
skip_cleanup: true
